version: '3'
services:
    api:
        build: ./
        command: npm run dev
        restart: always
        ports:
            - 7000:7000
        volumes:
            - ./src:/var/www/html/src
            - ./index.js:/var/www/html/index.js
        depends_on:
            - db
    db:
        image: mongo
        restart: always
        ports:
            - 27017:27017
        volumes:
            - ./data:/data/db